nums = [int(i) for i in raw_input().split()][1:]
a_1_nums = filter(lambda x: x % 5 == 0 and x % 2 == 0, nums)
a_2_nums = filter(lambda x: x % 5 == 1, nums)
a_3_nums = filter(lambda x: x % 5 == 2, nums)
a_4_nums = filter(lambda x: x % 5 == 3, nums)
a_5_nums = filter(lambda x: x % 5 == 4, nums)
a_1 = 'N' if len(a_1_nums) == 0 else sum(a_1_nums)
a_2 = 'N' if len(a_2_nums) == 0 else sum([x[0] * x[1] for x in zip(a_2_nums, [1, -1] * len(a_2_nums))])
a_3 = 'N' if len(a_3_nums) == 0 else len(a_3_nums)
a_4 = 'N' if len(a_4_nums) == 0 else '{:.1f}'.format(sum(a_4_nums) * 1.0 / len(a_4_nums))
a_5 = 'N' if len(a_5_nums) == 0 else max(a_5_nums)
print '{} {} {} {} {}'.format(a_1, a_2, a_3, a_4, a_5)